const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:3888/api";

export const PIPELINE_CONSTANTS = {
  API_BASE_URL,
  ENDPOINTS: {
    PIPELINE_PRODUCTS: "/pipeline-products",
    PIPELINE_LICENSES: "/pipeline-licenses",
    PIPELINE_RENTALS: "/pipeline-rentals",
    PIPELINE_PAYMENTS: "/pipeline-payments",
    PIPELINE: "/pipeline",
    LEADS: "/leads",
    OFFERS: "/offers",
    SALES: "/sales",
  },
  QUERY_KEYS: {
    PIPELINE_PRODUCTS: "pipeline-products",
    PIPELINE_LICENSES: "pipeline-licenses",
    PIPELINE_RENTALS: "pipeline-rentals",
    PIPELINE_PAYMENTS: "pipeline-payments",
    PIPELINE_HISTORY: "pipeline-history",
    LEADS: "leads",
    LEAD: "lead",
    LEAD_STATS: "lead-stats",
    OFFERS: "offers",
    OFFER: "offer",
    SALES: "sales",
    SALE: "sale",
    SALE_STATS: "sale-stats",
  },
  DEFAULT_PAGE_SIZE: 50,
  PAGE_SIZE_OPTIONS: [25, 50, 100, 200],
  CURRENCIES: [
    { id: "tl", name: "TL" },
    { id: "usd", name: "USD" },
    { id: "eur", name: "EUR" },
  ],
  BILLING_PERIOD_OPTIONS: [
    { id: "1", name: "Aylık" },
    { id: "3", name: "3 Aylık" },
    { id: "6", name: "6 Aylık" },
    { id: "12", name: "Yıllık" },
  ],
  LEAD_SOURCES: [
    { id: "web", name: "Web" },
    { id: "phone", name: "Telefon" },
    { id: "email", name: "E-posta" },
    { id: "referral", name: "Referans" },
    { id: "social", name: "Sosyal Medya" },
    { id: "event", name: "Etkinlik" },
    { id: "other", name: "Diğer" },
  ],
  PRIORITY_OPTIONS: [
    { id: "low", name: "Düşük" },
    { id: "medium", name: "Orta" },
    { id: "high", name: "Yüksek" },
    { id: "urgent", name: "Acil" },
  ],
  PAYMENT_METHODS: [
    { id: "cash", name: "Nakit" },
    { id: "bank-transfer", name: "Havale/EFT" },
    { id: "credit-card", name: "Kredi Kartı" },
    { id: "check", name: "Çek" },
    { id: "other", name: "Diğer" },
  ],
} as const;
