import { 
  LayoutDashboard, 
  FileText, 
  Plug,
  Users,
  Key,
  Package,
  Wallet,
  ScrollText,
  Bell,
  FileCheck,
  TrendingUp,
  UserCog,
  Shield,
  UserCircle,
  Building2,
  MessageSquarePlus,
} from "lucide-react";
import type { MenuItemProps } from "./SidebarMenuItem";
import { PERMISSIONS } from "../../../features/auth/constants/permissions";

export const sidebarMenuItems: MenuItemProps[] = [
  {
    icon: LayoutDashboard,
    label: "Dashboard",
    path: "/dashboard",
    requiredPermission: PERMISSIONS.DASHBOARD_VIEW,
  },
  {
    icon: FileText,
    label: "Kontrat",
    requiredPermission: PERMISSIONS.CONTRACT_MENU,
    subItems: [
      { label: "Kontratları Göster", path: "/contracts" },
      { label: "Kurulum Bekleyen Ürünler", path: "/contracts/pending-installations" },
      { label: "Faturasız Kalemler", path: "/contracts/uninvoiced-items" },
      { label: "Sözleşme Faturaları", path: "/contract-invoices" },
      { label: "Yazarkasalar", path: "/contracts/cash-registers", requiredPermission: PERMISSIONS.DASHBOARD_VIEW },
      { label: "Destekler", path: "/contracts/supports", requiredPermission: PERMISSIONS.DASHBOARD_VIEW },
      { label: "Versiyonlar", path: "/contracts/versions", requiredPermission: PERMISSIONS.DASHBOARD_VIEW },
      { label: "SaaS", path: "/contracts/saas", requiredPermission: PERMISSIONS.DASHBOARD_VIEW },
      { label: "Dökümanlar", path: "/contracts/documents" },
      { label: "Kıst Raporu", path: "/contracts/prorated-report" },
    ],
  },
  {
    icon: Users,
    label: "Müşteriler",
    path: "/customers",
    requiredPermission: PERMISSIONS.CUSTOMER_MENU,
  },
  {
    icon: Key,
    label: "Lisanslar",
    path: "/licenses",
    requiredPermission: PERMISSIONS.LICENSE_MENU,
  },
  {
    icon: Wallet,
    label: "Finans",
    requiredPermission: PERMISSIONS.FINANCE_MENU,
    subItems: [
      { label: "Faturalar", path: "/finance/invoices" },
      { label: "Alacak Listesi", path: "/finance/receivables" },
      { label: "Online Ödemeler", path: "/finance/payments" },
      { label: "Otomatik Ödemeler", path: "/finance/automated-payments" },
      { label: "Banka İşlemleri", path: "/finance/bank-transactions" },
      { label: "Enflasyon Oranları", path: "/finance/inflation-rates" },
    ],
  },
  {
    icon: Package,
    label: "Ürünler",
    requiredPermission: PERMISSIONS.SALES_MENU,
    subItems: [
      { label: "Donanım", path: "/products/hardware" },
      { label: "Yazılım", path: "/products/software" },
    ],
  },
  {
    icon: TrendingUp,
    label: "Satış Yönetimi",
    requiredPermission: PERMISSIONS.SALES_MENU,
    subItems: [
      { label: "Dashboard", path: "/sales", requiredPermission: PERMISSIONS.DASHBOARD_VIEW },
      { label: "Potansiyeller", path: "/leads" },
      { label: "Teklifler", path: "/offers" },
      { label: "Satışlar", path: "/pipeline/sales" },
      { label: "Pipeline Kanban", path: "/pipeline/kanban" },
    ],
  },
  {
    icon: Plug,
    label: "Entegratör",
    path: "/integrator",
    requiredPermission: PERMISSIONS.SALES_MENU,
  },
  {
    icon: FileCheck,
    label: "E-Belge",
    requiredPermission: PERMISSIONS.EDOC_MENU,
    subItems: [
      { label: "E-Belge Durumları", path: "/e-documents/statuses" },
      { label: "Üye Yönetimi", path: "/e-documents/members" },
      { label: "Kontör Yüklemeleri", path: "/e-documents/credits" },
      { label: "Fiyat Tanımları", path: "/e-documents/invoice-prices" },
    ],
  },
  {
    icon: ScrollText,
    label: "Sistem",
    requiredPermission: PERMISSIONS.SYSTEM_MENU,
    subItems: [
      { label: "Sistem Logları", path: "/system/logs" },
      { label: "Kullanıcı Yönetimi", path: "/system/users" },
      { label: "Firma Yönetimi", path: "/system/companies" },
    ],
  },
  {
    icon: Bell,
    label: "Bildirimler",
    path: "/system/notifications",
    requiredPermission: PERMISSIONS.NOTIFICATION_MENU,
  },
  {
    icon: Shield,
    label: "SSO Yönetimi",
    requiredPermission: PERMISSIONS.SSO_MANAGEMENT_MENU,
    subItems: [
      { label: "Dashboard", path: "/sso-management", requiredPermission: PERMISSIONS.DASHBOARD_VIEW },
      { label: "Uygulamalar", path: "/sso-management/apps" },
      { label: "Roller", path: "/sso-management/roles" },
      { label: "İzinler", path: "/sso-management/perms" },
      { label: "Kullanıcılar", path: "/sso-management/users" },
      { label: "API Anahtarları", path: "/sso-management/api-keys" },
      { label: "Kerzz Boss Kullanıcıları", path: "/boss-users" },
    ],
  },
  {
    icon: UserCircle,
    label: "Çalışan Profilleri",
    subItems: [
      { label: "Tüm Profiller", path: "/employee-profiles", requiredPermission: PERMISSIONS.EMPLOYEE_PROFILE_MENU },
      { label: "Profilim", path: "/my-profile" },
    ],
  },
  {
    icon: Building2,
    label: "Organizasyon Tanımları",
    requiredPermission: PERMISSIONS.EMPLOYEE_PROFILE_MENU,
    subItems: [
      { label: "Departmanlar", path: "/org-lookups/departments" },
      { label: "Ünvanlar", path: "/org-lookups/titles" },
      { label: "Lokasyonlar", path: "/org-lookups/locations" },
    ],
  },
  {
    icon: MessageSquarePlus,
    label: "Geribildirim",
    path: "/feedbacks",
    requiredPermission: PERMISSIONS.FEEDBACK_MENU,
  },
];
